using UnityEngine.UIElements;
namespace SF.UIElements
{
    public static class ListViewUtilities
    {
        /// <summary>
        /// This is the base part of a <see cref="ListView"/> name when generated by a property field.
        /// <remarks>
        ///  Just add the name of the property list being shown by the ListView with a dash in
        /// front of it to get the Unity generated name of the ListView.
        /// Example a List of a C# object called WeaponProperties will be name
        /// unity-list-WeaponProperties
        /// </remarks>
        /// </summary>
        public const string ListViewBaseName = "unity-list";

        public static string GetListViewName(string propertyName)
        {
            return $"{ListViewBaseName}-{propertyName}";
        }
    }
}
